/**
 * Every cue in the game, and the table of which action fires which.
 *
 * Clips are imported so Vite fingerprints them and rewrites the URL for the
 * `/twentyfour/` base — a hardcoded `/assets/...` path would 404 on Pages.
 * The three animal clips are recordings; everything else is generated by
 * `scripts/gen-sounds.mjs` from a physical model. Regenerate with:
 *
 *   node scripts/gen-sounds.mjs
 *
 * ── The cue table ────────────────────────────────────────────────────
 * Action                          Cue           Tier      Visual it rides on
 * ────────────────────────────────────────────────────────────────────
 * card lift (pointerdown)         lift          soft      .armed
 * wedge crossed during drag       wedge         whisper   operator turns white
 * drop target acquired            target        soft      target card lights
 * drop rejected                   reject        soft      .rejected shake
 * merge with +                    opAdd         soft      flyer + new value
 * merge with −                    opSub         soft      "
 * merge with ×                    opMul         soft      "
 * merge with ÷                    opDiv         soft      "
 * hand solved                     succeed       loud      celebration + praise
 * long wait on one hand           longWait      loud      nudge note
 * gave up                         giveUp        loud      shake + red, answer
 * dead end, no move left          deadEnd       soft      not-a-dead-end note
 * undo                            undo          whisper   tile returns
 * reset hand                      reset         whisper   tiles return
 * advance to next hand            advance       whisper   new cards
 * deck complete                   deckDone      loud      done screen
 * new personal best               best          loud      best line on record
 * beat the on-screen target       beatTarget    loud      target row
 * start run / accept challenge    cta           soft      screen change
 * Start Over armed                arm           whisper   button turns red
 * link copied                     copied        soft      "Copied"
 * replay / new deck / back / lang nav           whisper   screen change
 * tutorial step advanced          step          whisper   step change
 * ────────────────────────────────────────────────────────────────────
 *
 * `beatTarget` follows the "vs" time the play screen was showing, which is
 * whatever the field's best was when the run started. On a challenge that is
 * the sender; on a replay of your own deck it is your own previous run. Both
 * are the thing you were racing, so both get the same cue.
 *
 * Tiers exist because 23 cues at equal weight is fatigue, not feedback. The
 * gain is baked into the files, so nothing here has to know about it: `loud`
 * is five earned moments, `soft` is a direct response to a gesture, and
 * `whisper` fires constantly and sits at the edge of hearing.
 *
 * Everything fails soft. Autoplay policy blocks playback until the page has
 * been interacted with, decoding can fail, and a muted player wants silence:
 * none of that is allowed to interrupt a run, so every entry point swallows
 * its errors.
 */

import giveUpUrl from '../assets/dog_giveup_woof.mp3';
import longWaitUrl from '../assets/long_wait_meow.mp3';
import succeedUrl from '../assets/succeed_meow.mp3';

import advanceUrl from '../assets/cues/advance.wav';
import armUrl from '../assets/cues/arm.wav';
import beatTargetUrl from '../assets/cues/beatTarget.wav';
import bestUrl from '../assets/cues/best.wav';
import copiedUrl from '../assets/cues/copied.wav';
import ctaUrl from '../assets/cues/cta.wav';
import deadEndUrl from '../assets/cues/deadEnd.wav';
import deckDoneUrl from '../assets/cues/deckDone.wav';
import liftUrl from '../assets/cues/lift.wav';
import navUrl from '../assets/cues/nav.wav';
import opAddUrl from '../assets/cues/opAdd.wav';
import opDivUrl from '../assets/cues/opDiv.wav';
import opMulUrl from '../assets/cues/opMul.wav';
import opSubUrl from '../assets/cues/opSub.wav';
import rejectUrl from '../assets/cues/reject.wav';
import resetUrl from '../assets/cues/reset.wav';
import stepUrl from '../assets/cues/step.wav';
import targetUrl from '../assets/cues/target.wav';
import undoUrl from '../assets/cues/undo.wav';
import wedgeUrl from '../assets/cues/wedge.wav';

export type Cue =
  | 'giveUp'
  | 'longWait'
  | 'succeed'
  | 'advance'
  | 'arm'
  | 'beatTarget'
  | 'best'
  | 'copied'
  | 'cta'
  | 'deadEnd'
  | 'deckDone'
  | 'lift'
  | 'nav'
  | 'opAdd'
  | 'opDiv'
  | 'opMul'
  | 'opSub'
  | 'reject'
  | 'reset'
  | 'step'
  | 'target'
  | 'undo'
  | 'wedge';

const SOURCES: Record<Cue, string> = {
  giveUp: giveUpUrl,
  longWait: longWaitUrl,
  succeed: succeedUrl,
  advance: advanceUrl,
  arm: armUrl,
  beatTarget: beatTargetUrl,
  best: bestUrl,
  copied: copiedUrl,
  cta: ctaUrl,
  deadEnd: deadEndUrl,
  deckDone: deckDoneUrl,
  lift: liftUrl,
  nav: navUrl,
  opAdd: opAddUrl,
  opDiv: opDivUrl,
  opMul: opMulUrl,
  opSub: opSubUrl,
  reject: rejectUrl,
  reset: resetUrl,
  step: stepUrl,
  target: targetUrl,
  undo: undoUrl,
  wedge: wedgeUrl,
};

/** Pick the operator cue. Kept here so the Op -> sound mapping has one home. */
export function opCue(op: '+' | '-' | '*' | '/'): Cue {
  switch (op) {
    case '+':
      return 'opAdd';
    case '-':
      return 'opSub';
    case '*':
      return 'opMul';
    default:
      return 'opDiv';
  }
}

/**
 * Minimum gap between two plays of the same cue. A drag crosses wedge
 * boundaries several times a second and `target` re-fires whenever the pointer
 * slides between cards; without this, the drag sounds like a zipper.
 */
const THROTTLE_MS: Partial<Record<Cue, number>> = {
  wedge: 45,
  target: 60,
  lift: 60,
};

const KEY_MUTED = 'tf.muted';

export function isMuted(): boolean {
  try {
    return localStorage.getItem(KEY_MUTED) === '1';
  } catch {
    return false;
  }
}

export function setMuted(muted: boolean): void {
  try {
    localStorage.setItem(KEY_MUTED, muted ? '1' : '0');
  } catch {
    /* private browsing — the setting just will not survive a reload */
  }
}

/* One element per cue, reused. Constructing an Audio per play leaks elements
   on a long run and adds a fetch the first time each one is needed. */
const players = new Map<Cue, HTMLAudioElement>();
const lastPlayed = new Map<Cue, number>();

function player(cue: Cue): HTMLAudioElement | null {
  if (typeof Audio === 'undefined') return null;
  let el = players.get(cue);
  if (!el) {
    el = new Audio(SOURCES[cue]);
    el.preload = 'auto';
    players.set(cue, el);
  }
  return el;
}

export function play(cue: Cue): void {
  if (isMuted()) return;

  const gap = THROTTLE_MS[cue];
  if (gap !== undefined) {
    const now = performance.now();
    if (now - (lastPlayed.get(cue) ?? -Infinity) < gap) return;
    lastPlayed.set(cue, now);
  }

  const el = player(cue);
  if (!el) return;
  try {
    // Restart rather than ignore: two quick give-ups should sound twice.
    el.currentTime = 0;
    void el.play().catch(() => {});
  } catch {
    /* not fatal — the visual cue carries the same information */
  }
}

/**
 * Warm the decoder on the first gesture so the first cue is not late.
 *
 * Only the cues a player meets in their first few seconds: fetching all 23 on
 * one gesture is a burst of requests to pay for sounds most of which will not
 * be needed for minutes, and the rest load lazily on first play anyway.
 */
const PRIMED: readonly Cue[] = ['cta', 'lift', 'wedge', 'target', 'opAdd', 'opSub', 'opMul', 'opDiv', 'succeed'];

export function primeSounds(): void {
  if (isMuted()) return;
  for (const cue of PRIMED) player(cue)?.load();
}
